### ISSUE TITLE
Unicode characters on Android x86

### ISSUE THREAD

**Issue by lexerel** [brodysoft/cordova-plugin-sqlite-evplus-ext-common-free#5]
My app is using Crosswalk plugin, which compiles separate APKs for different architectures. I've tested my app on Android ARM v7 device and it is working as expected, but the same app compiled for x86 device displays HEX codes instead of Unicode characters, e.g. ?ffffffc5??ffffffa1? instead of š. I have been testing different versions of your SQLite plugins with Android NDK implementation, but it is the same.

It was working alright with cordova-sqlite-storage plugin.

**Comment by brody2consult** [comment]
This issue is already discussed in litehelpers/Cordova-sqlite-evcore-extbuild-free#19. I hope to resolve this issue on evcore within the next few weeks then incorporate into this plugin version.

**Comment by lexerel** [comment]
Thank you!

**Comment by brody2consult** [comment]
Should be fixed now, please report if you encounter any further issues.
